config/routes.rb
Rails.application.routes.draw do

  resources :nobreaks
  resources :funcionarios
  resources :turnos
  resources :cameras
  resources :sensores
  resources :teclados
  resources :central_de_alarmes
  resources :controlps
  resources :internets
  resources :dvrs
  resources :hds
  resources :sindicos
  resources :administradoras
  resources :contratos
  resources :clientes
  resources :cidades

end

app/models/administradora.rb
class Administradora < ActiveRecord::Base
	has_many :clientes
end

app/models/camera.rb
class Camera < ActiveRecord::Base
end

app/models/cidade.rb
class Cidade < ActiveRecord::Base
	has_many :clientes
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
  belongs_to :cidade 
  belongs_to :administradora
  belongs_to :contrato
  belongs_to :dvr
  belongs_to :internet 
end

app/models/contrato.rb
class Contrato < ActiveRecord::Base
	has_many :clientes
end

app/models/controlp.rb
class Controlp < ActiveRecord::Base
end

app/models/dvr.rb
class Dvr < ActiveRecord::Base
	has_many :clientes
end

app/models/funcionario.rb
class Funcionario < ActiveRecord::Base
  belongs_to :turno
end

app/models/hd.rb
class Hd < ActiveRecord::Base
	has_many :clientes
end

app/models/internet.rb
class Internet < ActiveRecord::Base
	has_many :clientes
end

app/models/nobreak.rb
class Nobreak < ActiveRecord::Base
	has_many :clientes
end

app/models/sensore.rb
class Sensore < ActiveRecord::Base
	has_many :clientes
end

app/models/sindico.rb
class Sindico < ActiveRecord::Base
	has_many :clientes
end

app/models/teclado.rb
class Teclado < ActiveRecord::Base
	has_many :clientes
end

app/models/turno.rb
class Turno < ActiveRecord::Base
end

app/controllers/administradoras_controller.rb
class AdministradorasController < ApplicationController
  before_action :set_administradora, only: [:show, :edit, :update, :destroy]

  # GET /administradoras
  # GET /administradoras.json
  def index
    @administradoras = Administradora.all
  end

  # GET /administradoras/1
  # GET /administradoras/1.json
  def show
  end

  # GET /administradoras/new
  def new
    @administradora = Administradora.new
  end

  # GET /administradoras/1/edit
  def edit
  end

  # POST /administradoras
  # POST /administradoras.json
  def create
    @administradora = Administradora.new(administradora_params)

    respond_to do |format|
      if @administradora.save
        format.html { redirect_to @administradora, notice: 'Administradora was successfully created.' }
        format.json { render :show, status: :created, location: @administradora }
      else
        format.html { render :new }
        format.json { render json: @administradora.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /administradoras/1
  # PATCH/PUT /administradoras/1.json
  def update
    respond_to do |format|
      if @administradora.update(administradora_params)
        format.html { redirect_to @administradora, notice: 'Administradora was successfully updated.' }
        format.json { render :show, status: :ok, location: @administradora }
      else
        format.html { render :edit }
        format.json { render json: @administradora.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /administradoras/1
  # DELETE /administradoras/1.json
  def destroy
    @administradora.destroy
    respond_to do |format|
      format.html { redirect_to administradoras_url, notice: 'Administradora was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_administradora
      @administradora = Administradora.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def administradora_params
      params.require(:administradora).permit(:nome, :telefone)
    end
end

app/helpers/administradoras_helper.rb
module AdministradorasHelper
end

app/helpers/cameras_helper.rb
module CamerasHelper
end

app/helpers/cidades_helper.rb
module CidadesHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/dvrs_helper.rb
module DvrsHelper
end

app/helpers/hds_helper.rb
module HdsHelper
end

app/helpers/turnos_helper.rb
module TurnosHelper
end

app/views/administradoras/_form.html.erb
<%= form_for @administradora, :html => { :class => "form-horizontal administradora" } do |f| %>

  <% if @administradora.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@administradora.errors.count, "error") %> prohibited this administradora from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @administradora.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nome, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :nome, :class => 'form-control' %>
    </div>
    <%=f.error_span(:nome) %>
  </div>
  <div class="form-group">
    <%= f.label :telefone, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :telefone, :class => 'form-control' %>
    </div>
    <%=f.error_span(:telefone) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                administradoras_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/administradoras/edit.html.erb
<%- model_class = Administradora -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/administradoras/index.html.erb
<%- model_class = Administradora -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:telefone) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @administradoras.each do |administradora| %>
      <tr>
        <td><%= link_to administradora.id, administradora_path(administradora) %></td>
        <td><%= administradora.nome %></td>
        <td><%= administradora.telefone %></td>
        <td><%=l administradora.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_administradora_path(administradora), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      administradora_path(administradora),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_administradora_path,
            :class => 'btn btn-primary' %>

app/views/administradoras/new.html.erb
<%- model_class = Administradora -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/administradoras/show.html.erb
<%- model_class = Administradora -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nome) %>:</strong></dt>
  <dd><%= @administradora.nome %></dd>
  <dt><strong><%= model_class.human_attribute_name(:telefone) %>:</strong></dt>
  <dd><%= @administradora.telefone %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              administradoras_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_administradora_path(@administradora), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              administradora_path(@administradora),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>