config/routes.rb
Rails.application.routes.draw do

  resources :nobreaks
  resources :funcionarios
  resources :turnos
  resources :cameras
  resources :sensores
  resources :teclados
  resources :central_de_alarmes
  resources :controlps
  resources :internets
  resources :dvrs
  resources :hds
  resources :sindicos
  resources :administradoras
  resources :contratos
  resources :clientes
  resources :cidades

end

app/models/administradora.rb
class Administradora < ActiveRecord::Base
	has_many :clientes
end

app/models/camera.rb
class Camera < ActiveRecord::Base
end

app/models/cidade.rb
class Cidade < ActiveRecord::Base
	has_many :clientes
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
  belongs_to :cidade 
  belongs_to :administradora
  belongs_to :contrato
  belongs_to :dvr
  belongs_to :internet 
end

app/models/contrato.rb
class Contrato < ActiveRecord::Base
	has_many :clientes
end

app/models/controlp.rb
class Controlp < ActiveRecord::Base
end

app/models/dvr.rb
class Dvr < ActiveRecord::Base
	has_many :clientes
end

app/models/funcionario.rb
class Funcionario < ActiveRecord::Base
  belongs_to :turno
end

app/models/hd.rb
class Hd < ActiveRecord::Base
	has_many :clientes
end

app/models/internet.rb
class Internet < ActiveRecord::Base
	has_many :clientes
end

app/models/nobreak.rb
class Nobreak < ActiveRecord::Base
	has_many :clientes
end

app/models/sensore.rb
class Sensore < ActiveRecord::Base
	has_many :clientes
end

app/models/sindico.rb
class Sindico < ActiveRecord::Base
	has_many :clientes
end

app/models/teclado.rb
class Teclado < ActiveRecord::Base
	has_many :clientes
end

app/models/turno.rb
class Turno < ActiveRecord::Base
end

app/controllers/hds_controller.rb
class HdsController < ApplicationController
  before_action :set_hd, only: [:show, :edit, :update, :destroy]

  # GET /hds
  # GET /hds.json
  def index
    @hds = Hd.all
  end

  # GET /hds/1
  # GET /hds/1.json
  def show
  end

  # GET /hds/new
  def new
    @hd = Hd.new
  end

  # GET /hds/1/edit
  def edit
  end

  # POST /hds
  # POST /hds.json
  def create
    @hd = Hd.new(hd_params)

    respond_to do |format|
      if @hd.save
        format.html { redirect_to @hd, notice: 'Hd was successfully created.' }
        format.json { render :show, status: :created, location: @hd }
      else
        format.html { render :new }
        format.json { render json: @hd.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hds/1
  # PATCH/PUT /hds/1.json
  def update
    respond_to do |format|
      if @hd.update(hd_params)
        format.html { redirect_to @hd, notice: 'Hd was successfully updated.' }
        format.json { render :show, status: :ok, location: @hd }
      else
        format.html { render :edit }
        format.json { render json: @hd.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hds/1
  # DELETE /hds/1.json
  def destroy
    @hd.destroy
    respond_to do |format|
      format.html { redirect_to hds_url, notice: 'Hd was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hd
      @hd = Hd.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hd_params
      params.require(:hd).permit(:capacidade, :tempo_de_gravacao)
    end
end

app/helpers/cameras_helper.rb
module CamerasHelper
end

app/helpers/cidades_helper.rb
module CidadesHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/dvrs_helper.rb
module DvrsHelper
end

app/helpers/hds_helper.rb
module HdsHelper
end

app/helpers/nobreaks_helper.rb
module NobreaksHelper
end

app/helpers/turnos_helper.rb
module TurnosHelper
end

app/views/hds/_form.html.erb
<%= form_for @hd, :html => { :class => "form-horizontal hd" } do |f| %>

  <% if @hd.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@hd.errors.count, "error") %> prohibited this hd from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @hd.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :capacidade, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :capacidade, :class => 'form-control' %>
    </div>
    <%=f.error_span(:capacidade) %>
  </div>
  <div class="form-group">
    <%= f.label :tempo_de_gravacao, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :tempo_de_gravacao, :class => 'form-control' %>
    </div>
    <%=f.error_span(:tempo_de_gravacao) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                hds_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/hds/edit.html.erb
<%- model_class = Hd -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/hds/index.html.erb
<%- model_class = Hd -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:capacidade) %></th>
      <th><%= model_class.human_attribute_name(:tempo_de_gravacao) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @hds.each do |hd| %>
      <tr>
        <td><%= link_to hd.id, hd_path(hd) %></td>
        <td><%= hd.capacidade %></td>
        <td><%= hd.tempo_de_gravacao %></td>
        <td><%=l hd.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_hd_path(hd), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      hd_path(hd),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_hd_path,
            :class => 'btn btn-primary' %>

app/views/hds/new.html.erb
<%- model_class = Hd -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/hds/show.html.erb
<%- model_class = Hd -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:capacidade) %>:</strong></dt>
  <dd><%= @hd.capacidade %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tempo_de_gravacao) %>:</strong></dt>
  <dd><%= @hd.tempo_de_gravacao %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              hds_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_hd_path(@hd), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              hd_path(@hd),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>