config/routes.rb
Rails.application.routes.draw do

  resources :nobreaks
  resources :funcionarios
  resources :turnos
  resources :cameras
  resources :sensores
  resources :teclados
  resources :central_de_alarmes
  resources :controlps
  resources :internets
  resources :dvrs
  resources :hds
  resources :sindicos
  resources :administradoras
  resources :contratos
  resources :clientes
  resources :cidades

end

app/models/administradora.rb
class Administradora < ActiveRecord::Base
	has_many :clientes
end

app/models/camera.rb
class Camera < ActiveRecord::Base
end

app/models/cidade.rb
class Cidade < ActiveRecord::Base
	has_many :clientes
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
  belongs_to :cidade 
  belongs_to :administradora
  belongs_to :contrato
  belongs_to :dvr
  belongs_to :internet 
end

app/models/contrato.rb
class Contrato < ActiveRecord::Base
	has_many :clientes
end

app/models/controlp.rb
class Controlp < ActiveRecord::Base
end

app/models/dvr.rb
class Dvr < ActiveRecord::Base
	has_many :clientes
end

app/models/funcionario.rb
class Funcionario < ActiveRecord::Base
  belongs_to :turno
end

app/models/hd.rb
class Hd < ActiveRecord::Base
	has_many :clientes
end

app/models/internet.rb
class Internet < ActiveRecord::Base
	has_many :clientes
end

app/models/nobreak.rb
class Nobreak < ActiveRecord::Base
	has_many :clientes
end

app/models/sensore.rb
class Sensore < ActiveRecord::Base
	has_many :clientes
end

app/models/sindico.rb
class Sindico < ActiveRecord::Base
	has_many :clientes
end

app/models/teclado.rb
class Teclado < ActiveRecord::Base
	has_many :clientes
end

app/models/turno.rb
class Turno < ActiveRecord::Base
end

app/controllers/teclados_controller.rb
class TecladosController < ApplicationController
  before_action :set_teclado, only: [:show, :edit, :update, :destroy]

  # GET /teclados
  # GET /teclados.json
  def index
    @teclados = Teclado.all
  end

  # GET /teclados/1
  # GET /teclados/1.json
  def show
  end

  # GET /teclados/new
  def new
    @teclado = Teclado.new
  end

  # GET /teclados/1/edit
  def edit
  end

  # POST /teclados
  # POST /teclados.json
  def create
    @teclado = Teclado.new(teclado_params)

    respond_to do |format|
      if @teclado.save
        format.html { redirect_to @teclado, notice: 'Teclado was successfully created.' }
        format.json { render :show, status: :created, location: @teclado }
      else
        format.html { render :new }
        format.json { render json: @teclado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teclados/1
  # PATCH/PUT /teclados/1.json
  def update
    respond_to do |format|
      if @teclado.update(teclado_params)
        format.html { redirect_to @teclado, notice: 'Teclado was successfully updated.' }
        format.json { render :show, status: :ok, location: @teclado }
      else
        format.html { render :edit }
        format.json { render json: @teclado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teclados/1
  # DELETE /teclados/1.json
  def destroy
    @teclado.destroy
    respond_to do |format|
      format.html { redirect_to teclados_url, notice: 'Teclado was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teclado
      @teclado = Teclado.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teclado_params
      params.require(:teclado).permit(:tipo, :quantidade)
    end
end

app/helpers/cameras_helper.rb
module CamerasHelper
end

app/helpers/cidades_helper.rb
module CidadesHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/dvrs_helper.rb
module DvrsHelper
end

app/helpers/hds_helper.rb
module HdsHelper
end

app/helpers/teclados_helper.rb
module TecladosHelper
end

app/helpers/turnos_helper.rb
module TurnosHelper
end

app/views/teclados/_form.html.erb
<%= form_for @teclado, :html => { :class => "form-horizontal teclado" } do |f| %>

  <% if @teclado.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@teclado.errors.count, "error") %> prohibited this teclado from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @teclado.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :tipo, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :tipo, :class => 'form-control' %>
    </div>
    <%=f.error_span(:tipo) %>
  </div>
  <div class="form-group">
    <%= f.label :quantidade, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :quantidade, :class => 'form-control' %>
    </div>
    <%=f.error_span(:quantidade) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                teclados_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/teclados/edit.html.erb
<%- model_class = Teclado -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/teclados/index.html.erb
<%- model_class = Teclado -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:tipo) %></th>
      <th><%= model_class.human_attribute_name(:quantidade) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @teclados.each do |teclado| %>
      <tr>
        <td><%= link_to teclado.id, teclado_path(teclado) %></td>
        <td><%= teclado.tipo %></td>
        <td><%= teclado.quantidade %></td>
        <td><%=l teclado.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_teclado_path(teclado), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      teclado_path(teclado),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_teclado_path,
            :class => 'btn btn-primary' %>

app/views/teclados/new.html.erb
<%- model_class = Teclado -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/teclados/show.html.erb
<%- model_class = Teclado -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:tipo) %>:</strong></dt>
  <dd><%= @teclado.tipo %></dd>
  <dt><strong><%= model_class.human_attribute_name(:quantidade) %>:</strong></dt>
  <dd><%= @teclado.quantidade %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              teclados_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_teclado_path(@teclado), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              teclado_path(@teclado),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>