config/routes.rb
Rails.application.routes.draw do

  resources :nobreaks
  resources :funcionarios
  resources :turnos
  resources :cameras
  resources :sensores
  resources :teclados
  resources :central_de_alarmes
  resources :controlps
  resources :internets
  resources :dvrs
  resources :hds
  resources :sindicos
  resources :administradoras
  resources :contratos
  resources :clientes
  resources :cidades

end

app/models/administradora.rb
class Administradora < ActiveRecord::Base
	has_many :clientes
end

app/models/camera.rb
class Camera < ActiveRecord::Base
end

app/models/central_de_alarme.rb
class CentralDeAlarme < ActiveRecord::Base
	has_many :clientes
end

app/models/cidade.rb
class Cidade < ActiveRecord::Base
	has_many :clientes
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
  belongs_to :cidade 
  belongs_to :administradora
  belongs_to :contrato
  belongs_to :dvr
  belongs_to :internet 
end

app/models/contrato.rb
class Contrato < ActiveRecord::Base
	has_many :clientes
end

app/models/controlp.rb
class Controlp < ActiveRecord::Base
end

app/models/dvr.rb
class Dvr < ActiveRecord::Base
	has_many :clientes
end

app/models/funcionario.rb
class Funcionario < ActiveRecord::Base
  belongs_to :turno
end

app/models/hd.rb
class Hd < ActiveRecord::Base
	has_many :clientes
end

app/models/internet.rb
class Internet < ActiveRecord::Base
	has_many :clientes
end

app/models/nobreak.rb
class Nobreak < ActiveRecord::Base
	has_many :clientes
end

app/models/sensore.rb
class Sensore < ActiveRecord::Base
	has_many :clientes
end

app/models/sindico.rb
class Sindico < ActiveRecord::Base
	has_many :clientes
end

app/models/teclado.rb
class Teclado < ActiveRecord::Base
	has_many :clientes
end

app/models/turno.rb
class Turno < ActiveRecord::Base
end

app/controllers/central_de_alarmes_controller.rb
class CentralDeAlarmesController < ApplicationController
  before_action :set_central_de_alarme, only: [:show, :edit, :update, :destroy]

  # GET /central_de_alarmes
  # GET /central_de_alarmes.json
  def index
    @central_de_alarmes = CentralDeAlarme.all
  end

  # GET /central_de_alarmes/1
  # GET /central_de_alarmes/1.json
  def show
  end

  # GET /central_de_alarmes/new
  def new
    @central_de_alarme = CentralDeAlarme.new
  end

  # GET /central_de_alarmes/1/edit
  def edit
  end

  # POST /central_de_alarmes
  # POST /central_de_alarmes.json
  def create
    @central_de_alarme = CentralDeAlarme.new(central_de_alarme_params)

    respond_to do |format|
      if @central_de_alarme.save
        format.html { redirect_to @central_de_alarme, notice: 'Central de alarme was successfully created.' }
        format.json { render :show, status: :created, location: @central_de_alarme }
      else
        format.html { render :new }
        format.json { render json: @central_de_alarme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /central_de_alarmes/1
  # PATCH/PUT /central_de_alarmes/1.json
  def update
    respond_to do |format|
      if @central_de_alarme.update(central_de_alarme_params)
        format.html { redirect_to @central_de_alarme, notice: 'Central de alarme was successfully updated.' }
        format.json { render :show, status: :ok, location: @central_de_alarme }
      else
        format.html { render :edit }
        format.json { render json: @central_de_alarme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /central_de_alarmes/1
  # DELETE /central_de_alarmes/1.json
  def destroy
    @central_de_alarme.destroy
    respond_to do |format|
      format.html { redirect_to central_de_alarmes_url, notice: 'Central de alarme was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_central_de_alarme
      @central_de_alarme = CentralDeAlarme.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def central_de_alarme_params
      params.require(:central_de_alarme).permit(:modelo)
    end
end

app/helpers/cameras_helper.rb
module CamerasHelper
end

app/helpers/central_de_alarmes_helper.rb
module CentralDeAlarmesHelper
end

app/helpers/cidades_helper.rb
module CidadesHelper
end

app/helpers/dvrs_helper.rb
module DvrsHelper
end

app/helpers/hds_helper.rb
module HdsHelper
end

app/helpers/turnos_helper.rb
module TurnosHelper
end

app/views/central_de_alarmes/_form.html.erb
<%= form_for @central_de_alarme, :html => { :class => "form-horizontal central_de_alarme" } do |f| %>

  <% if @central_de_alarme.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@central_de_alarme.errors.count, "error") %> prohibited this central_de_alarme from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @central_de_alarme.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :modelo, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :modelo, :class => 'form-control' %>
    </div>
    <%=f.error_span(:modelo) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                central_de_alarmes_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/central_de_alarmes/edit.html.erb
<%- model_class = CentralDeAlarme -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/central_de_alarmes/index.html.erb
<%- model_class = CentralDeAlarme -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:modelo) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @central_de_alarmes.each do |central_de_alarme| %>
      <tr>
        <td><%= link_to central_de_alarme.id, central_de_alarme_path(central_de_alarme) %></td>
        <td><%= central_de_alarme.modelo %></td>
        <td><%=l central_de_alarme.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_central_de_alarme_path(central_de_alarme), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      central_de_alarme_path(central_de_alarme),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_central_de_alarme_path,
            :class => 'btn btn-primary' %>

app/views/central_de_alarmes/new.html.erb
<%- model_class = CentralDeAlarme -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/central_de_alarmes/show.html.erb
<%- model_class = CentralDeAlarme -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:modelo) %>:</strong></dt>
  <dd><%= @central_de_alarme.modelo %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              central_de_alarmes_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_central_de_alarme_path(@central_de_alarme), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              central_de_alarme_path(@central_de_alarme),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>